# Generated by Django 3.0.5 on 2020-04-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to='hallOfFameClient.Exercise'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', related_query_name='score', to='hallOfFameClient.Student'),
        ),
    ]
