# Generated by Django 3.0.5 on 2020-05-08 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSubjectScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mean_value', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_score', to='hallOfFameClient.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatGroupStudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mean_value', models.FloatField()),
                ('value', models.SmallIntegerField()),
                ('stat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_students_score', to='hallOfFameClient.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_groups_score', to='hallOfFameClient.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatGroupScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mean_value', models.FloatField()),
                ('max_score', models.SmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_score', to='hallOfFameClient.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
