# Generated by Django 3.0.5 on 2020-04-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_value',
            new_name='value',
        ),
        migrations.AddField(
            model_name='group',
            name='lecturers',
            field=models.ManyToManyField(related_name='groups', to='hallOfFameClient.Lecturer'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hallOfFameClient.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hallOfFameClient.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hallOfFameClient.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='hallOfFameClient.Student'),
        ),
    ]
