# Generated by Django 3.0.5 on 2020-04-07 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hallOfFameClient.models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0002_auto_20200407_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallOfFameClient.Student', validators=[hallOfFameClient.models.IsInGroupValidator]),
        ),
    ]
