# Generated by Django 3.0.5 on 2020-05-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0002_statgroupscore_statgroupstudentscore_statsubjectscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statgroupstudentscore',
            name='stat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_students_score', to='hallOfFameClient.StatGroupScore'),
        ),
    ]
