# Generated by Django 3.0.5 on 2020-04-27 16:02

from django.db import migrations, models
import hallOfFameClient.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0003_auto_20200423_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='album_number',
            field=models.IntegerField(unique=True, validators=[hallOfFameClient.validators.validate_album_number]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
