# Generated by Django 3.0.5 on 2020-05-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0004_auto_20200508_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statgroupscore',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_score', to='hallOfFameClient.Group'),
        ),
        migrations.AlterField(
            model_name='statgroupstudentscore',
            name='stat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_students_score', to='hallOfFameClient.StatGroupScore'),
        ),
        migrations.AlterField(
            model_name='statgroupstudentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_groups_score', to='hallOfFameClient.Student'),
        ),
        migrations.AlterField(
            model_name='statsubjectscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_score', to='hallOfFameClient.Subject'),
        ),
    ]
