# Generated by Django 3.0.5 on 2020-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0005_auto_20200427_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lecturers',
            field=models.ManyToManyField(related_name='subjects', to='hallOfFameClient.Lecturer'),
        ),
    ]
