# Generated by Django 3.0.5 on 2020-05-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0006_statsubjectstudentscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsubjectstudentscore',
            name='stat_subject',
        ),
        migrations.AddField(
            model_name='statsubjectstudentscore',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stat_students_score', to='hallOfFameClient.Subject'),
            preserve_default=False,
        ),
    ]
