# Generated by Django 3.0.5 on 2020-05-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0008_auto_20200508_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveSubjectStudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_value', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_scores', to='hallOfFameClient.ArchiveRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arch_subjects_score', to='hallOfFameClient.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arch_students_score', to='hallOfFameClient.Subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveGroupStudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_value', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arch_students_score', to='hallOfFameClient.Group')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_scores', to='hallOfFameClient.ArchiveRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arch_groups_score', to='hallOfFameClient.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
