# Generated by Django 3.0.5 on 2020-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0009_archivegroupstudentscore_archiverecord_archivesubjectstudentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiverecord',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
