# Generated by Django 3.0.5 on 2020-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallOfFameClient', '0010_auto_20200512_1724'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.UniqueConstraint(fields=('exercise', 'student'), name='only one score per exercise for student'),
        ),
    ]
